sudo pip install flask==0.9
sudo pip install flask-login
sudo pip install flask-openid
sudo pip install flask-mail==0.7.6
sudo pip install sqlalchemy==0.7.9
sudo pip install flask-sqlalchemy==0.16
sudo pip install sqlalchemy-migrate==0.7.2
sudo pip install flask-whooshalchemy==0.55a
sudo pip install flask-wtf==0.8.4
sudo pip install pytz==2013b
sudo pip install flask-babel==0.8
sudo pip install flup
sudo pip install Flask-Uploads