"""empty message

Revision ID: 11acc6c5d6fb
Revises: 4db460b0f07e
Create Date: 2015-05-19 11:06:35.607000

"""

# revision identifiers, used by Alembic.
revision = '11acc6c5d6fb'
down_revision = '4db460b0f07e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('promocodes', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'promocodes')
    ### end Alembic commands ###
