"""empty message

Revision ID: 19bd6de52e4
Revises: 1f356ad4737f
Create Date: 2015-05-05 16:20:35.954000

"""

# revision identifiers, used by Alembic.
revision = '19bd6de52e4'
down_revision = '1f356ad4737f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasktable_LRN',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasktable_LRN')
    ### end Alembic commands ###
