"""empty message

Revision ID: 3c881c14a49d
Revises: 19bd6de52e4
Create Date: 2015-05-05 17:50:35.772000

"""

# revision identifiers, used by Alembic.
revision = '3c881c14a49d'
down_revision = '19bd6de52e4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasktable_PRC',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasktable_PRC')
    ### end Alembic commands ###
