"""empty message

Revision ID: 44f13a084c27
Revises: 11acc6c5d6fb
Create Date: 2015-05-27 10:32:50.014000

"""

# revision identifiers, used by Alembic.
revision = '44f13a084c27'
down_revision = '11acc6c5d6fb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userinfo_expert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('age', sa.Float(), nullable=True),
    sa.Column('gender', sa.Integer(), nullable=True),
    sa.Column('year_pro_play', sa.Float(), nullable=True),
    sa.Column('game_primary', sa.Text(), nullable=True),
    sa.Column('game_primary_id', sa.Integer(), nullable=True),
    sa.Column('game_primary_hoursweek', sa.Float(), nullable=True),
    sa.Column('game_primary_yearsplayed', sa.Float(), nullable=True),
    sa.Column('game_secondary', sa.Text(), nullable=True),
    sa.Column('game_secondary_id', sa.Integer(), nullable=True),
    sa.Column('game_secondary_hoursweek', sa.Float(), nullable=True),
    sa.Column('game_secondary_yearsplayed', sa.Float(), nullable=True),
    sa.Column('specific_dota2_mmr', sa.Float(), nullable=True),
    sa.Column('specific_starcraft2_wcspoitns', sa.Float(), nullable=True),
    sa.Column('specific_counterstrike_teamrating', sa.Float(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'user', sa.Column('userinfo_expert_completed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'user', 'userinfo_expert_completed')
    op.drop_table('userinfo_expert')
    ### end Alembic commands ###
