"""empty message

Revision ID: 4e6e81664f8b
Revises: f36e97b8590
Create Date: 2015-05-10 19:32:37.871000

"""

# revision identifiers, used by Alembic.
revision = '4e6e81664f8b'
down_revision = 'f36e97b8590'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasktable_SYM',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('driftrate', sa.Float(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasktable_SYM')
    ### end Alembic commands ###
