"""empty message

Revision ID: 5d52042b0c9
Revises: 44f13a084c27
Create Date: 2015-07-16 15:28:22.517000

"""

# revision identifiers, used by Alembic.
revision = '5d52042b0c9'
down_revision = '44f13a084c27'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userinfo_expert', sa.Column('specific_counterstrike_skillgroup', sa.Text(), nullable=True))
    op.add_column('userinfo_expert', sa.Column('specific_counterstrike_skillgroup_id', sa.Integer(), nullable=True))
    op.add_column('userinfo_expert', sa.Column('specific_starcraft2_battlenetleague', sa.Text(), nullable=True))
    op.add_column('userinfo_expert', sa.Column('specific_starcraft2_battlenetleague_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userinfo_expert', 'specific_starcraft2_battlenetleague_id')
    op.drop_column('userinfo_expert', 'specific_starcraft2_battlenetleague')
    op.drop_column('userinfo_expert', 'specific_counterstrike_skillgroup_id')
    op.drop_column('userinfo_expert', 'specific_counterstrike_skillgroup')
    ### end Alembic commands ###
