"""empty message

Revision ID: f36e97b8590
Revises: 3c881c14a49d
Create Date: 2015-05-05 18:36:08.450000

"""

# revision identifiers, used by Alembic.
revision = 'f36e97b8590'
down_revision = '3c881c14a49d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasktable_PRC', sa.Column('driftrate', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasktable_PRC', 'driftrate')
    ### end Alembic commands ###
